apiVersion: v2
name: hetzner-storage-box-prometheus-exporter
description: A Helm chart for the Hetzner Storage Box Prometheus Exporter
type: application
version: 0.8.0 # x-releaser-pleaser-version
appVersion: "0.8.0" # x-releaser-pleaser-version
