version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

kos:
  - id: hetzner-storage-box-prometheus-exporter
    main: .
    base_image: alpine
    repositories:
      - ghcr.io/lukasmetzner/hetzner-storage-box-prometheus-exporter
    platforms:
      - linux/amd64
      - linux/arm64
    bare: true
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
