apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hetzner-storage-box-prometheus-exporter.fullname" . }}
  labels:
    {{- include "hetzner-storage-box-prometheus-exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hetzner-storage-box-prometheus-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hetzner-storage-box-prometheus-exporter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:v{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 2112
              protocol: TCP
          env:
            - name: HETZNER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.key }}
            - name: SCRAPE_INTERVAL
              value: {{ .Values.scrapeInterval | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
