name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: pre-commit/action@v3.0.1
