# .github/workflows/release.yml
name: goreleaser

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write
  # issues: write
  # id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      # More assembly might be required: Docker logins, GPG, etc.
      # It all depends on your needs.
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Helm
        uses: yokawasa/action-setup-kube-tools@v0.13.4
        with:
          setup-tools: helm
          helm: v4.1.1 # renovate: datasource=github-releases depName=helm/helm

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package Helm chart
        run: helm package chart/

      - name: Push Helm chart to GHCR
        run: helm push hetzner-storage-box-prometheus-exporter-*.tgz oci://ghcr.io/lukasmetzner/charts
